### ISSUE TITLE
Process of converting the decads into months

### ISSUE THREAD

**Issue by SaumikMallik** [wfpidn/SPI#1]
In step 3.7 why do we need to extract dekad 1,2 and 3 into separate files when we want to calculate monthly SPI values? Aren't we getting 3 different SPI values for a single month in the process (each for decad 1, 11 and 21)? 
I am not familiar what cdo is doing under the hood, so kind of confused with the process of converting the decad data into monthly data. Could you please elaborate on this?

**Comment by bennyistanto** [comment]
The idea of this approach is to get more frequent monitoring for SPI 1 - 72, and updated every dekad. To answer your question why we need to extract dekad data into separate files, see below illustration.
<img width="1346" alt="Screen Shot 2020-11-30 at 8 41 26 AM" src="https://user-images.githubusercontent.com/722584/100560301-f853ae80-32e7-11eb-9af7-a8545b68a897.png">

SPI script will read the netcdf input file based on time dimension. It means if we leave the data as is (without extracting) and would like to calculate SPI3, then the script will use data: Jan 2020 D3, Feb 2020 D1, Feb 2020 D2 (see row 13 column DEF on above picture), and this is not correct. I hope its clear now.

Well if you are confused with my approach using dekad data, maybe you could try using monthly data - https://data.chc.ucsb.edu/products/CHIRPS-2.0/global_monthly/netcdf/chirps-v2.0.monthly.nc and skip step 3.5 and 3.7.

**Comment by SaumikMallik** [comment]
Thank you for explaining the process so well! This is a much improved approach than the ARSET one.
