### ISSUE TITLE
Getting error : Conflicting sizes for dimension 'lat': length 12 on the data but length 170 on coordinate 'lat'

### ISSUE THREAD

**Issue by alperdincer** [wfpidn/SPI#3]
We are trying to calculate SPI for an area with the help of your tutorial and we are getting the following error when running the following command : 

Cmd : spi --periodicity monthly --scales 1 3 6 9 12 24 --calibration_start_year 1981 --calibration_end_year 2021 --netcdf_precip ./nc_files/tr_chirps-v2.0.monthly_3.nc --var_name_precip precip --output_file_base /datadrv/chirps_data/output_nc/tr_chirps --multiprocessing all --save_params /datadrv/chirps_data/tr_chirps_fitting.nc --overwrite

Error : ValueError: conflicting sizes for dimension 'lat': length 12 on the data but length 170 on coordinate 'lat'

The output of ncdump of the input file is as follow : 

netcdf tr_chirps-v2.0.monthly_3 {
dimensions:
	time = UNLIMITED ; // (486 currently)
	lon = 434 ;
	lat = 170 ;
variables:
	float time(time) ;
		time:standard_name = "time" ;
		time:units = "days since 1980-1-1 0:0:0" ;
		time:calendar = "gregorian" ;
		time:axis = "T" ;
	float lon(lon) ;
		lon:standard_name = "longitude" ;
		lon:long_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
	float lat(lat) ;
		lat:standard_name = "latitude" ;
		lat:long_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
	float precip(time, lat, lon) ;
		precip:standard_name = "convective precipitation rate" ;
		precip:long_name = "Climate Hazards group InfraRed Precipitation with Stations" ;
		precip:units = "mm" ;
		precip:_FillValue = -9999.f ;
		precip:missing_value = -9999.f ;
		precip:time_step = "month" ;
		precip:geostatial_lat_min = -50.f ;
		precip:geostatial_lat_max = 50.f ;
		precip:geostatial_lon_min = -180.f ;
		precip:geostatial_lon_max = 180.f ;

We can't find out the problem. We also tried to do analysis with GeoTiff option and we got the same error. Any suggestions?

**Comment by bennyistanto** [comment]
Could you upload your data tr_chirps-v2.0.monthly_3.nc? So I can check it. 

It would be good to post your issue in https://github.com/monocongo/climate_indices because it's related to the package. I am only use it and try to documented the step.

**Comment by alperdincer** [comment]
File is 149 MB so I uploaded to dropbox. You can download it from the following link : https://www.dropbox.com/s/fxf35cld2la5xi7/tr_chirps-v2.0.monthly_3.nc?dl=0 

I'll also open an issue in the package repo, but any help will be appreciated. Thanks for checking the file.

**Comment by bennyistanto** [comment]
@alperdincer I am sorry I could not help with your error.

But, it's worked on my Mac. For complete calculation from SPI-1 to SPI-72 only takes around 30minutes. I have uploaded all the result, feel free to use it. https://www.dropbox.com/sh/12gkofha9x8vx0l/AADaYNXldjRg8PU_ZZauZmpsa?dl=0

<img width="752" alt="Screen Shot 2021-08-12 at 8 18 26 PM" src="https://user-images.githubusercontent.com/722584/129203856-0869cc4e-0ad2-4711-a014-f70b72b20016.png">

**Comment by alperdincer** [comment]
thanks @bennyistanto for the results. I think there is a problem with my linux machine. I'll try it on my Mac tomorrow.

**Comment by alperdincer** [comment]
dear @bennyistanto, i have checked your SPI calculation results in QGIS and the location of the results are not correct. Somehow the output coordinates are not matching with the input. Can you check the results?

**Comment by bennyistanto** [comment]
I have checked it, and perfectly match with your input data. 
You may not open the nc output directly to QGIS, but convert it to GeoTIFF using GDAL and dont forget to put `-a_ullr 24.375 34.225 46.025 42.675 EPSG:4326`

Follow to guideline in point 7.

https://user-images.githubusercontent.com/722584/133986463-f1c2bff1-6497-40a8-86e1-33383e4757f8.mov

**Comment by alperdincer** [comment]
Thanks for the info @bennyistanto. It is interesting to learn that every NetCDF file is not working with QGIS. 

One more thing, do you suggest any resource to calculate the mean value in a polygon as a time series within NetCDF files? 

Best regards.

Alper.
